### ISSUE TITLE
save game logs to home directory on linux into .ozymandias folder

### ISSUE THREAD

**Issue by dalerank** [dalerank/Ozymandias#6]

**Comment by akuskis** [comment]
Do you mean the folder with game sources?

**Comment by akuskis** [comment]
On Linux it prints logs to the standard output, so maybe saving logs is not necessary. What do you think?

**Comment by dalerank** [comment]
I think not all users can take log from console, better save it somewhere, data folder ok, but it may be another folder  like .ozymandias in home

**Comment by akuskis** [comment]
If user cant start applicaiton on Linux with redirecting its output to file, then getting access to invisible folder also can cause problems for this user (as this folder will be invisble because of dot). In addition we will create some mess in his home folder by adding yet another invisible folder.

That is why better to use folder with game files. User already know where this folder is and have seen some files there. Also looks like it is a place where logs under windows are stored. So it should give better experience.

**Comment by dalerank** [comment]
Yep, good idea, exe cant start without data dir
